"""Modernized single-file version of the original main.py demo.

Changes from the original template:
  - `BeeAgent`            -> `RequirementAgent`      (current BeeAI API)
  - `OllamaChatModel(...)` -> `ChatModel.from_name("ollama:granite4:micro")`
  - the mock weather record -> a *weather SPARQL spec* generated by Mellea and executed
    against a real (small) RDF graph.

The reusable implementation lives in `src/weather_graph/`; this file is a flat, readable
walkthrough of the same five steps for anyone reading the demo top-to-bottom.

Run: `uv run python main.py`  (requires Ollama with `granite4:micro`).
"""

from __future__ import annotations

import asyncio
import json

from beeai_framework.agents.requirement import RequirementAgent
from beeai_framework.agents.requirement.requirements.conditional import ConditionalRequirement
from beeai_framework.backend import ChatModel
from beeai_framework.middleware.trajectory import GlobalTrajectoryMiddleware
from beeai_framework.tools import StringToolOutput, tool

# 1. Structured target + 2. Mellea generative w/ requirements loop (see src/weather_graph)
from weather_graph.generation import generate_spec
from weather_graph.sparql import run_query


# 3. Expose the Mellea-backed capability as a BeeAI-compatible tool
@tool
def weather_tool(question: str) -> StringToolOutput:
    """Answer a weather question by generating and running a validated SPARQL query."""
    spec = generate_spec(question)  # Mellea handles validation + self-correction
    result = run_query(spec.sparql)
    return StringToolOutput(result=json.dumps({"sparql": result.sparql, "rows": result.rows}))


# 4. Initialize a RequirementAgent on a local Ollama model, forcing the tool to run first
llm = ChatModel.from_name("ollama:granite4:micro")
agent = RequirementAgent(
    llm=llm,
    tools=[weather_tool],
    requirements=[ConditionalRequirement(weather_tool, force_at_step=1, only_success_invocations=False)],
    role="Weather Graph Analyst",
    instructions="Answer only from weather_tool's returned rows; never invent numbers.",
)


# 5. Run the agent task asynchronously
async def main() -> None:
    response = await agent.run(
        "What is the weather like in Chicago right now and is it warm?"
    ).middleware(GlobalTrajectoryMiddleware())
    print(getattr(getattr(response, "answer", None), "text", response))


if __name__ == "__main__":
    asyncio.run(main())
